[package]
name = "scrap"
version = "0.1.0"
authors = ["m3y <ma3ya.ozw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
